/**
 * ClaudeShop seed script — creates a demo tenant with sample catalog,
 * customers, and an admin AuthUser (email: demo@claudeshop.local,
 * password: demo-admin-1234).
 *
 * Invoked via `pnpm db:seed`.
 */
import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import bcrypt from 'bcryptjs';
import { createPrismaClient, withTenant } from './client';

const DEMO_ADMIN_EMAIL = 'demo@claudeshop.local';
const DEMO_ADMIN_PASSWORD = 'demo-admin-1234';

/**
 * Persist the demo tenant's identifiers (and admin credentials) to a
 * handful of files so the storefront + admin can address the tenant
 * without the operator hand-editing envs:
 *
 *   <repo>/.env.seeded                 audit-trail (text, gitignored)
 *   <repo>/apps/storefront/.env.local  picked up by Next.js at dev time
 *   <repo>/apps/admin/.env.local       picked up by Next.js at dev time
 *
 * The files are overwritten on every seed run — re-seeding with a
 * different tenant id Just Works.
 */
function writeSeedArtefacts(args: {
  tenantId: string;
  tenantSlug: string;
}): void {
  const repoRoot = resolve(dirname(new URL(import.meta.url).pathname), '../../..');
  const iso = new Date().toISOString();
  const payload = [
    '# Auto-generated by packages/db/src/seed.ts — DO NOT edit by hand.',
    '# Regenerated on every `pnpm db:seed`. Safe to delete if you want to',
    '# force the storefront/admin to fall back to the slug lookup path.',
    `SEEDED_AT=${iso}`,
    `SEEDED_DEMO_TENANT_ID=${args.tenantId}`,
    `SEEDED_DEMO_TENANT_SLUG=${args.tenantSlug}`,
    `SEEDED_DEMO_ADMIN_EMAIL=${DEMO_ADMIN_EMAIL}`,
    `SEEDED_DEMO_ADMIN_PASSWORD=${DEMO_ADMIN_PASSWORD}`,
    '',
  ].join('\n');

  // Root audit-trail file
  writeFileSync(resolve(repoRoot, '.env.seeded'), payload, { encoding: 'utf8' });

  // Per-app .env.local so Next.js picks it up automatically.
  // We write the two vars each app actually reads — no more.
  const appEnv = [
    '# Auto-generated by packages/db/src/seed.ts — safe to delete.',
    '# Overwritten on every `pnpm db:seed`. Gitignored by convention.',
    `NEXT_PUBLIC_SEEDED_DEMO_TENANT_ID=${args.tenantId}`,
    `SEEDED_DEMO_TENANT_ID=${args.tenantId}`,
    `SEEDED_DEMO_TENANT_SLUG=${args.tenantSlug}`,
    '',
  ].join('\n');
  for (const app of ['apps/storefront', 'apps/admin']) {
    const envPath = resolve(repoRoot, app, '.env.local');
    try {
      mkdirSync(dirname(envPath), { recursive: true });
      writeFileSync(envPath, appEnv, { encoding: 'utf8' });
    } catch (err) {
      // eslint-disable-next-line no-console
      console.warn(`[seed] could not write ${envPath}:`, err);
    }
  }

  // eslint-disable-next-line no-console
  console.info(
    `[seed] wrote .env.seeded + apps/*/.env.local → tenant ${args.tenantSlug} (${args.tenantId})`,
  );
}

async function main() {
  const prisma = createPrismaClient();

  try {
    const demoTenant = await prisma.tenant.upsert({
      where: { slug: 'demo' },
      create: {
        slug: 'demo',
        name: 'Demo Store',
        plan: 'PRO',
        settings: {
          currency: 'EUR',
          defaultLocale: 'en',
          locales: ['en', 'fr', 'de', 'es'],
        },
      },
      update: {},
    });

    // eslint-disable-next-line no-console
    console.info(`Demo tenant ready: ${demoTenant.id} (${demoTenant.slug})`);

    writeSeedArtefacts({ tenantId: demoTenant.id, tenantSlug: demoTenant.slug });

    await withTenant(prisma, demoTenant.id, async (tx) => {
      const product = await tx.product.upsert({
        where: { tenantId_slug: { tenantId: demoTenant.id, slug: 'hello-claudeshop-tee' } },
        create: {
          tenantId: demoTenant.id,
          slug: 'hello-claudeshop-tee',
          status: 'ACTIVE',
          type: 'VARIABLE',
          name: {
            en: 'Hello ClaudeShop T-Shirt',
            fr: 'T-Shirt Hello ClaudeShop',
            de: 'Hello ClaudeShop T-Shirt',
            es: 'Camiseta Hello ClaudeShop',
          },
          description: {
            en: 'A 100% organic cotton tee — proof that ClaudeShop can sell things.',
            fr: 'T-shirt coton bio 100% — preuve que ClaudeShop sait vendre.',
          },
          seo: {
            title: { en: 'Hello ClaudeShop Tee', fr: 'T-shirt Hello ClaudeShop' },
            description: { en: 'The iconic demo tee.', fr: 'Le t-shirt démo iconique.' },
          },
          variants: {
            create: [
              { sku: 'HCS-TEE-S', options: { size: 'S', color: 'black' }, weight: '0.2' },
              { sku: 'HCS-TEE-M', options: { size: 'M', color: 'black' }, weight: '0.22' },
              { sku: 'HCS-TEE-L', options: { size: 'L', color: 'black' }, weight: '0.24' },
            ],
          },
        },
        update: {},
      });
      // eslint-disable-next-line no-console
      console.info(`Seeded product: ${product.slug}`);

      // Phase 15 — seed PriceSets so the storefront PDP shows real prices.
      const variants = await tx.variant.findMany({
        where: { productId: product.id },
        select: { id: true, sku: true },
      });
      for (const v of variants) {
        for (const { currency, amount } of [
          { currency: 'EUR', amount: '29.90' },
          { currency: 'USD', amount: '32.00' },
        ]) {
          await tx.priceSet.upsert({
            where: {
              variantId_currency_channel: {
                variantId: v.id,
                currency,
                channel: 'default',
              },
            },
            create: {
              variantId: v.id,
              currency,
              channel: 'default',
              amount,
              taxIncluded: false,
            },
            update: {},
          });
        }
      }
      // eslint-disable-next-line no-console
      console.info(`Seeded ${variants.length * 2} PriceSets (EUR + USD per variant)`);

      const apparel = await tx.category.upsert({
        where: { tenantId_slug: { tenantId: demoTenant.id, slug: 'apparel' } },
        create: {
          tenantId: demoTenant.id,
          slug: 'apparel',
          name: { en: 'Apparel', fr: 'Vêtements' },
          position: 1,
        },
        update: {},
      });
      await tx.category.upsert({
        where: { tenantId_slug: { tenantId: demoTenant.id, slug: 'accessories' } },
        create: {
          tenantId: demoTenant.id,
          slug: 'accessories',
          name: { en: 'Accessories', fr: 'Accessoires' },
          position: 2,
        },
        update: {},
      });
      await tx.categoryOnProduct.upsert({
        where: {
          productId_categoryId: { productId: product.id, categoryId: apparel.id },
        },
        create: { productId: product.id, categoryId: apparel.id },
        update: {},
      });
      // eslint-disable-next-line no-console
      console.info('Seeded categories: apparel + accessories');

      await tx.customer.upsert({
        where: { tenantId_email: { tenantId: demoTenant.id, email: 'demo@claudeshop.local' } },
        create: {
          tenantId: demoTenant.id,
          email: 'demo@claudeshop.local',
          firstName: 'Demo',
          lastName: 'Shopper',
          group: 'B2C',
        },
        update: {},
      });
      // eslint-disable-next-line no-console
      console.info('Seeded customer: demo@claudeshop.local');

      const passwordHash = await bcrypt.hash(DEMO_ADMIN_PASSWORD, 12);
      await tx.authUser.upsert({
        where: { tenantId_email: { tenantId: demoTenant.id, email: DEMO_ADMIN_EMAIL } },
        create: {
          tenantId: demoTenant.id,
          email: DEMO_ADMIN_EMAIL,
          passwordHash,
          role: 'OWNER',
          displayName: 'Demo Owner',
          emailVerified: true,
        },
        update: {},
      });
      // eslint-disable-next-line no-console
      console.info(
        `Seeded admin user: ${DEMO_ADMIN_EMAIL} / ${DEMO_ADMIN_PASSWORD} (OWNER)`,
      );

      await tx.page.upsert({
        where: { tenantId_slug: { tenantId: demoTenant.id, slug: 'about' } },
        create: {
          tenantId: demoTenant.id,
          slug: 'about',
          status: 'PUBLISHED',
          publishedAt: new Date(),
          title: {
            en: 'About ClaudeShop',
            fr: 'À propos de ClaudeShop',
          },
          body: {
            en:
              '# About ClaudeShop\n\n' +
              'ClaudeShop is a Claude-native business OS — catalog, orders, payments,\n' +
              'and a merchant copilot all under one repo.\n\n' +
              '- Open source (Apache-2.0)\n' +
              '- Multi-tenant with Postgres RLS\n' +
              '- Semantic search via pgvector\n',
            fr:
              '# À propos de ClaudeShop\n\n' +
              'ClaudeShop est un OS de commerce natif Claude — catalogue, commandes,\n' +
              'paiements et copilote marchand dans un seul repo.\n\n' +
              '- Open source (Apache-2.0)\n' +
              '- Multi-tenant avec RLS Postgres\n' +
              '- Recherche sémantique via pgvector\n',
          },
        },
        update: {},
      });
      // eslint-disable-next-line no-console
      console.info('Seeded CMS page: /about');
    });
  } finally {
    await prisma.$disconnect();
  }
}

main().catch((err) => {
  // eslint-disable-next-line no-console
  console.error(err);
  process.exit(1);
});
